levelup
Teaching-projects/SZE-MOSZE-2020-Cminusminus pull request #6
Opened 2020-10-14 08:25 UTC by kurucc

@hegyhati be tudnád taggelni @oliverosz-t?

2020-10-17 10:59 UTC, oliverosz requested changes

2020-10-17 10:59 UTC, oliverosz commented on character.cpp
> +#include <math.h>
`<cmath>`

2020-10-17 10:59 UTC, oliverosz commented on player.cpp
> +#include <math.h>
`<cmath>`

2020-10-17 10:59 UTC, oliverosz commented on player.cpp
> +	if (xp >= 100)
Ez a feltétel felesleges, ha hamis, akkor úgyse fut le a ciklus.

2020-10-17 10:59 UTC, oliverosz commented on player.h
> +	void XPManager(const Player& player);
Ez ne egy publikus metódus legyen. Ne az osztály használójának kelljen figyelnie a szintlépésre, hanem automatikusan történjen meg a támadáskor.

2020-10-17 10:59 UTC, oliverosz commented on player.cpp
> +	xp += player.GetDamage();
Ha az ellenségnek kevesebb életereje volt, mint amennyi a sebzés, akkor csak a tényleges sebzés után kapjon xp-t.

2020-10-17 11:26 UTC, kurucc commented
@oliverosz megcsináltam a kért módosításokat.

2020-10-17 13:02 UTC, oliverosz requested changes
Még pár kisebb javítanivaló van. Ha azok megvannak, akkor lehet frissíteni a branchet a masterre, és oldjátok fel a conflictokat.

2020-10-17 13:02 UTC, oliverosz commented on player.cpp
> +	XPManager(*this, enemy);
A `*this`t nem kell átadni, ez egy tagfüggvény.

2020-10-17 13:02 UTC, oliverosz commented on player.cpp
> +void Player::Attack(Player& enemy) {
Az ősosztálynak is van `Attack` metódusa, ennek azt kellene override-olnia. És nem látom okát, hogy csak másik `Player`t tudjon támadni, `Character`t ne.

2020-10-17 13:29 UTC, kurucc commented
@oliverosz készen vannak a kért változtatások. Ez így jó lesz?
Valamint még lenne egy olyan kérdésem, hogy a conflictokat úgy kellene megoldani, hogy a jelenleg a masteren lévő dolgokat bele kellene helyezni a level up-os kódomba, vagy ezt hogy kellene lekezelni?

2020-10-17 13:34 UTC, oliverosz commented
> @oliverosz készen vannak a kért változtatások. Ez így jó lesz?

Jó.

> Valamint még lenne egy olyan kérdésem, hogy a conflictokat úgy kellene megoldani, hogy a jelenleg a masteren lévő dolgokat bele kellene helyezni a level up-os kódomba, vagy ezt hogy kellene lekezelni?

Igen, a "belehelyezés" történhet merge, rebase vagy felőlem akár cherry-pick útján is. Eközben fognak jeletkezni conflictok, amiket manuálisan kell feloldani az összefésült kódban.

2020-10-17 15:35 UTC, kurucc commented
@oliverosz megcsináltam a conflictokat. Jó lesz így?

2020-10-17 15:56 UTC, oliverosz requested changes
@kurucc Majdnem jó. A mainben még van egy kis hiba. És mivel most már a masteren is minden dokumentálva van, az ehhez a feature-höz készített metódusok is legyenek dokumentálva, meg majd a további feladatoknál is ugyanígy.

2020-10-17 15:56 UTC, oliverosz commented on main.cpp
> +		  p2 = static_cast<Player*>(Character::parseUnit(argv[1]));
Ezt a castolás itt nem jó, és amúgy ha exceptiont dob valami, akkor memory leak maradhat, mert a catch blokkban nincs felszabadítás.

2020-10-17 15:56 UTC, oliverosz commented on character.h
> +  void GainDamage(const double multiplier);
Az új metódusok is legyenek most már dokumentálva.

2020-10-17 22:13 UTC, kurucc commented
@oliverosz megcsináltam a metódusok leírását, és a castot is átírtam. Így jó lesz?

2020-10-17 22:23 UTC, oliverosz commented
@kurucc Nem, nem jó. A static_cast és a zárójeles C-style cast ugyanaz, nem az volt a baj. A baj az, hogy a `Character::parseUnit` egy `Character`t hoz létre és adja vissza a címét, amit hiába castolsz át `Player*`ra, attól az még egy `Character`re fog mutatni. És ez hibás, mert a `Character`nek meg nincs XP adattagja például.

2020-10-17 23:12 UTC, kurucc commented
@oliverosz elvileg kijavítottam a problémát

2020-10-18 05:22 UTC, oliverosz approved these changes

2020-10-18 05:23 UTC, merged